apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-efs-provisioner
resources:
- github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/dev/?ref=master
