apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    workload-type: kfserving  
spec:
  default:
    predictor:
      serviceAccountName: default-editor
      tensorflow:
        storageUri: "s3://raffa-ai-models/flowers"