apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: flowers-sample
spec:
  name: flowers-sample
  #protocol: kfserving
  predictors:
  - graph:
      implementation: TENSORFLOW_SERVER
      modelUri: s3://raffa-ai-models/flowers
      name: flower-classifier
    name: default-predictor
    replicas: 1
--- 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flowers-sample-http-classifier
  namespace: raffa
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /seldon/raffa/flowers-sample-classifier/
      rewrite:
        uri: /
      route:
        - destination:
            host: flowers-sample-default-predictor-flower-classifier
            port:
              number: 9000
