apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: istio-injection
spec:
  match:
    scope: Namespaced
    kinds:
      - apiGroups: 
        - ''
        kinds: 
        - Pod
      # - apiGroups: ["apps"]
      #   kinds: ["ReplicaSet","StatefulSet","Deployment"]
      # - apiGroups: ["batch"]
      #   kinds: ["Job","CronJob"]                                       
  location: "metadata.annotations.'sidecar.istio.io/inject'"
  parameters:
    assign:
      value: "true"