apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: kubeflow-user
spec:
  provider: my_htpasswd_provider
  #name: {{ index (lookup "user.openshift.io/v1" "Identity" "" (index .Identities 0)).Extra "email" }}
  templates:
  - objectTemplate: |
      apiVersion: kubeflow.org/v1beta1
      kind: Profile
      metadata:
        name: {{ .Name }}
      spec:
        owner:
          kind: User
          name: {{ .Name }}
        resourceQuotaSpec:
          hard:
            cpu: "8"
            memory: 16Gi
            "requests.nvidia.com/gpu": "10"
            persistentvolumeclaims: "10"
            requests.storage: "200Gi"
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kubeflow-editor
        namespace: {{ .Name }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kubeflow-edit
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}  
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name }}-sm-view
        namespace: ${sm_cp_namespace}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}                   