apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: test-user-config
spec:
  provider: my_htpasswd_provider
  #name: {{ index (lookup "user.openshift.io/v1" "Identity" "" (index .Identities 0)).Extra "email" }}
  templates:
  - objectTemplate: |
      apiVersion: kubeflow.org/v1beta1
      kind: Profile
      metadata:
        name: {{ .Name }}
      spec:
        owner:
          kind: User
          name: {{ .Name }}
        resourceQuotaSpec:
          hard:
            cpu: "4"
            memory: 8Gi
            "requests.nvidia.com/gpu": "1"
            persistentvolumeclaims: "10"
            requests.storage: "20Gi"