apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: sts-role-annotation-injection
spec:
  match:
    scope: Namespaced
    kinds:
      - apiGroups: 
        - ''
        kinds: 
        - ServiceAccount                                    
  location: "metadata.annotations.'eks.amazonaws.com/role-arn'"
  parameters:
    assign:
      value: "${role_arn}"      




     